= Mensago Client-Server API
Jon Yoder <jsyoder@mailfence.com>
v1.0, 2019-08-10

*Status:* Draft (incomplete) +
*Abstract:* Spec for Mensago client-server communications

== Description

Client-server communications on the Mensago platform take inspiration from a number of other of protocols that have gone before it, including https://tools.ietf.org/html/rfc1939[POP3], http://www.courier-mta.org/cone/smap1.html[SMAP], and https://jmap.io/spec.html[JMAP]. The protocol operates under three guiding principles:

[arabic]
. Minimal Metadata: The server must know only the bare minimum amount of information necessary to perform its duties.
. Guarded Trust: Trust in an entity (user, device, server, etc.) does not imply free rein for that entity. Data is still checked for integrity, steps are taken to prevent abuse, and boundaries are kept to prevent problems from scaling larger. For example, a friend may be unaware that he or she has been compromised and has a device that is attempting to send out spam. Thus, even though the device is given a level of trust, boundaries for behavior are maintained.
. Safety and Portability: technologies leveraged for the Mensago platform have been chosen for their portability and/or safety so that it is possible to run a Mensago server on NetBSD just as easily as on Windows.
. The responsibilities of the server are:
* To provide a transport mechanism for messages to and from other servers.
* To provide a synchronization mechanism for a user’s devices.
* To provide identity services

Communication between Mensago clients and servers is a synchronous text-based protocol which operates on TCP port 2001. The protocol is line-oriented and meant to be easy to parse and validate. Client-server commands focus on authentication, synchronization, and message delivery because client data is encrypted by default.

== Technology Conventions

Compatibility with POP, IMAP, and SMTP has prompted great heroics in the more than 40 years since e-mail’s invention, but these protocols are the root cause behind the many problems which plague modern e-mail. A fresh start is needed, based on best-of-breed technologies and methods available now.

Like those that came before, Mensago' client-server protocol is text-based for greater flexibility and easier troubleshooting. UTF-8 is the default text encoding to provide a well-supported means of representing text for all communities. JSON is used for data serialization because it is human-readable, flexible, easy to parse, and easy to validate. The version of Base85 encoding defined in https://tools.ietf.org/html/rfc1924[RFC 1924] is smaller than Base64 and designed to be compatible with source code. It is the standard encoding except where noted.

Strong, efficient, and proven algorithms are used for encryption. ChaCha20 and Elliptic Curve 25519 are preferred algorithms for symmetric and asymmetric encryption, respectively. BLAKE2b is a fast hashing algorithm which yields comparable or better results than SHA2 and SHA3 algorithms. Argon2id is utilized for password hashing. SHA2-256, AES-256 and the 2048- and 4096-bit versions of RSA are options for environments which require certified algorithms.

== Client Items

The Mensago server's main role is storage and synchronization of opaque data files called *client items*. These JSON-formatted text files contain an encrypted payload, where the actual message content is stored, and some minimal metadata in its header.

*TODO:* Message format sample here

*Client Item Fields*

Version::
REQUIRED. A numeric string set to the client item API version. Until such time after this standard has reached final 1.0 status, this will be set to "1.0".

KeyHash::
REQUIRED. A hash of the encryption key used. The hash itself is Base85-encoded and is prefixed by the algorithm used, which can be `BLAKE2B-256`, `SHA-256`, `SHA512`, `SHA3-256`, or `SHA3-512`. `BLAKE2B-256` is preferred because of its speed apart from hardware acceleration.

Payload::
REQUIRED. A string containing the real data for the item, encrypted and Base85-encoded. The unencrypted payload is JSON data, but the schema is context-specific. For speed, a symmetric key is used to encrypt the payload. The algorithm must be `AES256`, `AES128`, or `XSALSA20`. The XSalsa20 cipher uses Poly1305 for message authentication and the AES ciphers use GCM. XSalsa20 is preferred because it is faster overall without depending on hardware acceleration.

== Limitations, Maximums, and Timeouts

Maximum line size for the Mensago protocol is measured in bytes, not characters, due to the varying size of UTF-8 code points. Each line in the protocol is expected to be terminated by a carriage return and line feed character pair (CR-LF, `\r\n`). In order to accommodate 4096-bit RSA keys, one line in an client-server message may be up to 8KiB (8192 bytes), including the line terminator. Similar to http://www.courier-mta.org/cone/smap1.html[SMAP], Mensago commands and replies MUST be no more than 16 KiB (16384 bytes) including line ending. This maximum applies only to commands and replies themselves and not to file transfer data.

Although client items have no theoretical size limit, there are some practical limits placed on user messages. For efficency of transmission and storage, messages SHOULD be no more than 50 MiB. Server administrators MAY impose a hard limit of some size, but it SHOULD be no less than this. Client items not scheduled for delivery MAY be of any size, although server administrators MAY impose a maximum size for client items in general.

As part of the Guarded Trust principle and also general resource conservation, there are some soft limitations imposed on clients. An individual device is limited to 25 recipients per minute. This is a configurable soft default limit. It is intended to prevent spam and Reply All storms and encourage more thoughtful inclusion of others in group conversations.

Idle sessions MAY be ended by a server. A server MUST wait a minimum of 30 minutes before terminating a connection. Likewise, clients which are left idle for extended periods of time should wait no more than 29 minutes to periodically send `NOOP` commands to keep the connection alive, although a client's update polling may make this unnecessary. 

In order to prevent a denial-of-service on servers which permit public account registration, by default a server limits account registration to once per 10 minute time period from an individual IP address. This timeout does not apply to an administrator creating accounts locally on the server itself. 10 minutes is the default, but an administrator may change this value.

== Filesystem Access

Because a server is not permitted to know more than is necessary about the information it processes, the filesystem itself utilizes opaque, but unique, identifiers for files and directories.

Universally Unique Identifiers (UUIDs) are used extensively. Files utilize a three-part naming system, consisting of the number of seconds since the UNIX epoch, the size of the file in bytes, and the file’s  version 4 UUID. An example looks like this: `1535760000.9457.8ba70831-d189-4aaa-b6e6-5cca0823b205`. Directories also  utilize UUIDs instead of alphanumeric names.

Server-side paths are represented in a unique way: the start of the path is always a single slash (`/`) followed by directory elements. Each directory element is separated by a space. Because filesystem entries  follow a very specific format, accounting for whitespace and special  characters in paths is not necessary. An example path looks like this: `/ 0cfb91e8-256b-420b-b37d-db28004120f5 aa7347c1-a837-460f-8cf0-698d4411758a ac7971bf-fe44-400c-8605-eb499b9274ad`. Server-side paths are always absolute–relative references -- using `.` and `..` are not supported, and any path using them MUST be rejected. Path references are always relative to the root directory of a workspace; no access outside of the workspace directory hierarchy is permitted for any client.

Although there is a standard filesystem layout for Mensago workspace  data, the server is not responsible for creating any directories; it is all handled by the client. Clients are expected to maintain a mapping of the real name of a directory in the workspace to the UUID used for its name on the server side. A malicious actor with server access is able to obtain very little useful information about any of the files stored on the system.

== Settings Sync and Server-Side Storage

In order to provide the highest level of privacy and security for user data, the server is given a minimal level of trust. This means that it can be utilized for basic functions to assist client software, but all user data must be inaccessible from the server side.

Server-side storage for data other than client items should be stored in the `/ settings` directory. Device-specific key exchange archives should be stored here. Client software may also store application-specific settings information in an encrypted archive file, as well. Although JSON is recommended as a storage format inside the encrypted archive, the exact format is determined by the application.

The name of the settings file is determined by the client software. The file is expected to be encrypted by a key used just for settings storage. The recommended format for maximum privacy is to use the first 32 characters of the Base64-encoded hash of the encryption key followed by a period and a number indicating the version. An example would look like this: `f9c9e42c25002e7148dceea7d687fea89.23`.

The device-checking feature of Mensago Identity Services provides a relatively painless form of multifactor authentication while also providing a way for new devices to receive the keys used by clients. Specific information on this process can be found in the Identity Services design document.

== Command Reference

For any command listed below, `400 BAD REQUEST` is returned by the  server if a command does not match expected syntax. It also may be returned if a command argument contains invalid data.

=== COPY

_Copies an item from the selected directory to another on the server_

[cols="1,3a"]
|===
| Parameters | * SourceFile
* DestDir
| Returns | * 200 OK
** NewName
| Possible Errors 
| * 404 NOT FOUND
* 409 QUOTA UNSUFFICIENT
|===

Creates a duplicate of an item and returns the name of the item as determined by the server. Each file on the server is expected to have a unique name, so the name of the copy is returned if successful. The destination path is expected to be a list of directories. If there is not sufficient space in the filesystem or the workspace quota, `409 QUOTA INSUFFICIENT` is returned. `404 NOT FOUND` is returned if the item or the destination directory does not exist.

=== DELETE 

_Deletes a file from the current directory_

[cols="1,3a"]
|===
| Parameters | * Path
| Returns | * 200 OK
| Possible Errors 
| * 404 NOT FOUND
|===

Deletes a file from the current directory.

=== DELIVER

_Transfers an item from one identified server to another_

[cols="1,3a"]
|===
| Parameters | * Size
* Hash
* Destination
| Returns | * 200 OK
| Possible Errors 
| * 404 NOT FOUND
|===

A server may issue this command ONLY after receiving a `200 OK` from a SERVERPWD command. It operates much like the UPLOAD and SEND commands. The actual DELIVER command is a request for upload, submitting the size of the item in bytes, a hash of the item in CrytoString format, and the destination domain of the recipient. If the specified domain does not exist, `404 NOT FOUND` is returned and the error is logged by the receiving server. Aside from this, the commands continue in the same way as UPLOAD and SEND, including handling of lack of space, interruptions, and resuming.

404 errors are logged by servers receiving delivered items to ensure good behavior and prevent spam. Should the number of permitted delivery failures of this type exceed the limit configured on the server, `307 DELIVERY FAILURE LIMIT EXCEEDED` is returned and the connection is closed. By default, this threshold is recommended to be 500, but it can be configured to be more or less permissive. The offending server is not banned, but a configurable cooldown period must pass before delivery may be attempted. The default cooldown period is 60 minutes. If the offending server attempts to deliver before the cooldown has expired, it will receive a `308 DELIVERY DELAY NOT REACHED` response to the SERVERID command. Server implementors MAY want to log the sending workspace whenever a 404 error is received and ensure that a few misbehaving workspaces do not cause a delivery delay for the entire server to a particular domain.

=== DOWNLOAD

_Download an item from the selected directory_

[cols="1,3a"]
|===
| Parameters | * Path
* _optional:_ Offset
| Returns | * 100 Continue
** Size
* 200 OK
| Possible Errors 
| * 404 NOT FOUND
|===

The client downloads data from a file on the server. The client first makes the request, which includes name of the file in the current directory. Assuming that all goes well, the server returns `100 CONTINUE` along with the size of the file in bytes. The client acknowledges readiness for the transfer by resending the DOWNLOAD command with the size given by the server attached in the Size field. The server then transmits the data. If an offset is supplied by the client, the server is expected to begin transmission starting at the specified offset in order to resume a previously-interrupted transmission.

=== EXISTS

_Checks for the existence of a file or directory on the server_

[cols="1,3a"]
|===
| Parameters | * Path
| Returns | * 200 OK

| Possible Errors 
| * 404 NOT FOUND
|===

Returns `200 OK` if the file or directory exists.

=== GETQUOTAINFO

_Gets the disk quota size and disk usage for the current workspace. Administrators may request the quota for other workspaces._

[cols="1,3a"]
|===
| Parameters | * Workspaces (administrator only)
| Returns | * 200 OK
** QuotaSize
** DiskUsage

| Possible Errors 
| * 404 NOT FOUND
* 403 FORBIDDEN
* 414 LIMIT REACHED
|===

GETQUOTAINFO obtains the disk quota value for the current workspace. The QuotaSize value returned is the disk quota measured in mebibytes. The DiskUsage value returned is measured in bytes for greater precision. An administrator account can also include a comma-separated list of workspace IDs in the Workspaces parameter to obtain the disk quota size and disk usage for other workspaces. Up to 100 workspace IDs may be specified in this manner, and the values in QuotaSize and DiskUsage will be comma-separated values in the same order as the workspaces were specified. If issued the Workspace parameter is included in the command when issued by a non-administrator, `403 FORBIDDEN` is returned. `414 LIMIT REACHED` is returned if an administrator requests more than 100 workspaces at once.

=== GETUPDATES

_Requests all changes since the time specified_

[cols="1,3a"]
|===
| Parameters | * Time
| Returns | * 200 OK
** Updates
** Remaining
|===

The client requests a list of updates since the requested time. Time is submitted in seconds since the Epoch (UNIX time), UTC time. The server responds with `200 OK` and the list of updates in the Updates field. The updates themselves are returned in chronological order from oldest to newest.

The Remaining field exists for circumstances where there are an unusually large number of updates requested. The field contains the number of updates not returned by the server. Server implementors would be wise to set a maximum number of updates returned by one transation.

There are three types of updates: CREATE, DELETE, and MOVE.

....
Updates : [
	{	"Type" : "Create", 
		"Path" : "/ 721a1b2f-8703-4d23-8f9e-7275c647b63e 1579216613.5143.ec795b28-ea77-4b5d-b860-6d484222feb1" 
	},
	{	"Type" : "Move",
		"Source" : "/ 721a1b2f-8703-4d23-8f9e-7275c647b63e 1579216613.5143.ec795b28-ea77-4b5d-b860-6d484222feb1",
		"Destination" : "/ ec795b28-ea77-4b5d-b860-6d484222feb1" 
	},
	{	"Type" : "Delete",
		"Path" : "/ ec795b28-ea77-4b5d-b860-6d484222feb1 1579216613.5143.ec795b28-ea77-4b5d-b860-6d484222feb1"
	}
]
....

`Create` and `Delete` updates list the full path of the new item and is received even if the item is not part of the selected directory. `Move` updates follow the format of the MOVE command, providing the full path of the item prior to the move and then the new directory to which it was moved.

=== LIST

_Gets list of items in selected directory_

[cols="1,3a"]
|===
| Parameters | * _optional:_ Path
* _optional:_ Time
| Returns | * 200 OK
** Files
| Possible Errors 
| * 404 NOT FOUND
|===

Obtains a list of the entries in the specified directory or the current one if not specified. This command will return entries which only matches the expected filename format on the server side, consisting of a timestamp, file size, and file UUID, all three joined together with periods. This command takes an optional timestamp parameter. As with GETUPDATES, the timestamp is expected to be submitted in seconds since the Epoch (UNIX time), UTC time. If provided, only the files created at or after the timestamp are returned. If omitted or set to zero, all items in the current directory are returned. The server's response, if 200 OK, will also contain the Files field which is a list type field containing the names of the files.

=== LISTDIRS

_Gets list of subdirectories of the selected directory_

[cols="1,3a"]
|===
| Parameters | * _optional:_ Path
| Returns | * 200 OK
** Directories
| Possible Errors 
| * 404 NOT FOUND
|===

Returns a list of the subdirectories of the specified directory or the current one if not specified. The Directories field will be a list type field each of the directories' names.

=== MKDIR

_Creates a new directory_

[cols="1,3a"]
|===
| Parameters | * Path
| Returns | * 200 OK

| Possible Errors 
| * 408 RESOURCE EXISTS
|===

Create a workspace directory. The directory path is a standard Mensago server-side path which indicates the path to be created relative to the root of the workspace. The command works similarly to the UNIX command `mkdir -p`, which creates directorys and parent directorys as needed to ensure that the entire path exists. If the leaf already exists, `408 RESOURCE EXISTS` is returned.

=== MOVE

_Moves an item from the selected path to another on the server_

[cols="1,3a"]
|===
| Parameters | * SourceFile
* DestDir
| Returns | * 200 OK
| Possible Errors 
| * 404 NOT FOUND
* 408 RESOURCE EXISTS
|===

Moves an item. The item is expected to be in the current directory and may be a file or subdirectory. The destination path is expected to be a standard Mensago server-side path to a directory. `404 NOT FOUND` is returned if the item does not exist. `404 RESOURCE EXISTS` is returned if an entry in the destination already exists with that name.

=== RMDIR

_Deletes a directory_

[cols="1,3a"]
|===
| Parameters | * Path
* _optional:_ Recursive
| Returns | * 200 OK

| Possible Errors 
| * 404 NOT FOUND
* 408 RESOURCE EXISTS
|===

Deletes a workspace directory. The directory path is a standard Mensago server-side path which indicates the path to be created relative to the root of the workspace. If the Recursive flag is set to true, the command recursively deletes the directory and all of its contents. If the Recursive flag is set to false, a non-empty directory will cause a 408 RESOURCE EXISTS error.

=== SELECT

_Sets the current directory for the session_

[cols="1,3a"]
|===
| Parameters | * Path
| Returns | * 200 OK
| Possible Errors 
| * 404 NOT FOUND
|===

If the path does not exist or the path is not permitted, such as one which is out of the permitted filesystem area, `404 RESOURCE NOT FOUND` is returned. The path is a standard Mensago filesystem path.

=== SEND

_Sends an item to another server_

[cols="1,3a"]
|===
| Parameters | * Size
* Hash
* _resume only:_ Name
* _resume only:_ Offset
| Returns | * 200 OK
** FileName
| Possible Errors 
| * 404 NOT FOUND
* 409 QUOTA INSUFFICIENT
* 414 LIMIT REACHED
|===

This command works exactly like UPLOAD except that the server processes it for delivery to another domain instead of for local storage. The message uploaded is expected to have encrypted delivery information sections for both the sending and receiving servers. Items uploaded via SEND without delivery information are should be expected to be deleted by the server.

=== UPLOAD
_Upload an item to the server_

[cols="1,3a"]
|===
| Parameters | * Size
* Hash
* Path
* _resume only:_ TempName
* _resume only:_ Offset
| Returns | * 100 CONTINUE
** TempName
* 200 OK
** FileName
| Possible Errors 
| * 404 NOT FOUND
* 409 QUOTA INSUFFICIENT
* 410 HASH MISMATCH
* 414 LIMIT REACHED
* 309 ALGORITHM NOT SUPPORTED
|===

The client uploads data to a file on the server. First is the request for the upload, submitting the size of the upload in bytes, the hash value computed on the client side in CryptoString format, and the location to which the file is to be uploaded. The size is expected to be accurate, as the data is treated as binary and will not be reformatted or otherwise modified. `409 QUOTA INSUFFICIENT` is returned if the workspace does not have sufficient space (or if the filesystem on the server lacks sufficient space). If the client is cleared for upload after all server-side checks are complete, `100 CONTINUE` is returned along with the name of the temporary file used to store the data during upload. Once the upload is complete, the server calculates the hash value of the data received, and if the value matches that sent by the client, `200 OK` is returned along with the name of the file in its requested location. If the hashes do not match, `410 HASH MISMATCH` is returned, the temporary file is deleted, and the client will need to attempt the upload again. 

If the upload is somehow interrupted, the client can request resuming a previous upload. To finish the upload, the UPLOAD command must be sent a second time with all previous fields along with TempName and Offset fields, where TempName contains the name of the file initially given by the server and Offset containing the starting point to resume the upload. The rest of the process continues as normal until the file is uploaded. Note that if the server does not support the requested algorithm for the hash, `309 ALGORITHM NOT SUPPORTED` will be returned.

== Administrator Command Reference

=== SETQUOTA

_Sets the disk quota for one or more workspaces_

[cols="1,3a"]
|===
| Parameters | * Workspaces
* Size
| Returns | * 200 OK

| Possible Errors 
| * 404 NOT FOUND
* 403 FORBIDDEN
|===

SETQUOTA customizes a workspace's disk quota size. The Size parameter is measured in mebibytes and is expected to be an integer greater than 0. The Workspaces parameter is a string containing a comma-separated list of workspace IDs. If issued by a non-administrator, `403 FORBIDDEN` is returned. Note that if the quota for a workspace has been set to a value less than its current disk usage, the workspace will be unable to send messages or upload any new user files until either the quota increased to greater than its usage or the usage is decreased to less than its quota.


== Status Codes

Most commands require the context of an authenticated login session. Attempts to use such a command outside of an authenticated session will result in a `401 UNAUTHORIZED` response. Likewise, if a user does not have sufficient permissions to execute a command or execute a command on a specific client item, `403 FORBIDDEN` is returned.

* 1xx: Info Codes
** 100 Continue
** 101 Pending
** 102 Item
** 103 Update
** 104 Transfer
* 2xx: Success Codes
** 200 OK
** 201 Registered
** 202 Unregistered
* 3xx: Server-Related Error Codes
** 300 Internal Server Error
** 301 Not implemented
** 302 Server maintenance
** 303 Server unavailable
** 304 Registration closed
** 305 Interrupted
** 306 Key failure
** 307 Delivery failure limit exceeded
** 308 Delivery delay not reached
** 309 Algorith not supported
* 4xx: Client-Related Codes
** 400 Bad Request
** 401 Unauthorized
** 402 Authentication Failure
** 403 Forbidden
** 404 Not Found
** 405 Terminated
** 406 Payment Required
** 407 Unavailable
** 408 Resource Exists
** 409 Quota Insufficient
** 410 Hash Mismatch
** 411 Bad Keycard Data
** 412 Noncompliant Keycard Data
** 413 Invalid Signature
** 414 Limit Reached
** 415 Expired
