= Mensago Contact Information and Address Books
:author: Jon Yoder
:email: jon@yoder.cloud
:revdate: 2021-05-01
:revnumber: 1.1
:description: Structure and description of Mensago contact information and processes
:keywords: Mensago, contacts, pip
:toc: preamble
:table-stripes: odd

*Status:* Draft (incomplete) +
*Abstract:* Mensago contact information and processes

== Description

Contact information and address book synchronization are one reason Mensago is a platform and not merely a new e-mail application. This document describes how Mensago contact information is structured, stored, communicated, and shared.

== Structure

Like other Mensago data, contact information is normally stored in JSON format. The overall structure is a dictionary containing information grouped into sub-dictionaries by privacy level.

At the top level, a contact contains two dictionaries: the header and a privacy group. The header contains a high-level description of the information, including the API version, the source of the information, and the type of entity described. A short example of the format is shown below.

[source,json]
----
{
    "Header" : {
        "Version" : "1.0",
        "EntityType" : "individual",
        "Update" : "no",
    },
    "Public" : {
        "GivenName" : "Fred",
        "FamilyName" : "Kingsley",
        "Gender" : "male",
        "Mensago" : {
            "Home" : {
                "UserID" : "fkingsley",
                "Workspace" : "3f258107-19aa-43c1-86c6-30e3914e18b8",
                "Domain" : "example.com",
            }
        },
    },
    "Private" : {
        "Birthday" : "19860314",
    },
    "Secret" : {
        "Mensago" : {
            "Home" : {
                "Keys" : {
                    "Verify" : {
                        "KeyHash" : "BLAKE2B-256:#ksGJdu4{=P3@UdZ787UB>kZ%S4bze?G?9uhF4fo",
                        "Value" : "ED25519:te#3G{*qG&_rK<Pfd6EWVeU_$){-Wxh|&+Gj)S<G"
                    },
                    "Encrypt" : {
                        "KeyHash" : "BLAKE2B-256:)}sRcq+f=Kyx2tg03mPbIq`>_u!ha4*pa0n$u!)v",
                        "Value" : "CURVE25519:)r)+9^WCSo!5s~9ru~Vy0`CcP$|Cees`oh9+I6ZT"
                    }
                }
            }
        },
    }
}
----

=== Privacy Groups

Individuals and organizations alike have certain contact information which they share freely and other contact information which is more carefully guarded. Privacy Groups enable a user to easily and quickly decide what information is shared or not shared. A contact file can contain multiple privacy groups so that those people with whom the information is shared knows how carefully to guard said information. The names of the three privacy groups are `Public`, `Private`, and `Secret` in order of least private to most. Privacy Groups can also be customized. For example, a user may opt to include their mailing address in the Public group. In this case, all initial Contact Request messages, described later in this document, will be sent including this mailing address. 

Public:: Information permitted to be visible by essentially anyone. When a Contact Request message is sent to someone, information in this Privacy Group is included automatically. By default the following fields are set to this level: `FormattedName`, `GivenName`, `FamilyName`, `Gender`, `Prefixes`, `Suffixes`, and all `Mensago` fields except `Keys`. If a Mensago client implements introductions, only information at this level may be shared with others.

Private:: Information that is more carefully controlled; most contact information fields are found in this privacy group by default. If a contact request is sent including this level of information, information from the Public level is also included, but information from this level overrides any field in the Public group. In this way, for example, a person may use a very generic `Public` avatar and an actual photo used at the `Private` level.

Secret:: Information that must be explicitly shared. Information in this group cannot be shared in an initial (Stage 1) Contact Request message, but can be included in later parts of the process. Mensago cryptography keys are in this group. The user may choose to put other fields in the `secret` group or may provide different values for this group in one or more fields.

*Example:*

Below is listed an example of a profile which utilizes most of the available fields so that the structure of a contact can be better understood. 

[source,json]
----
{
    "Header" : {
        "Version" : "1.0",
        "EntityType" : "individual",
        "Update" : "no",
    },

    "Public" : {
        "FormattedName" : "Richard Brannan",
        "GivenName" : "Richard",
        "FamilyName" : "Brannan",
        "Gender" : "Male",
        "Prefixes" : [ "Mr." ],
        "Suffixes" : [ "Ph. D" ],
        "Mensago" : {
            "Home" : {
                "UserID" : "cavs4life",
                "Workspace" : "e3e98b45-b226-4926-b4ea-69ab16dd035e",
                "Domain" : "mensago-example.com",
            }
        },
    },

    "Private" : {
        "Nicknames" : [ "Rick" ],
        "AdditionalNames" : [ "Michael" ],

        "MailingAddresses" : {
            "Work" : {
                "StreetAddress" : "1013 Hickman St.",
                "ExtendedAddress" : "Suite D",
                "Locality" : "Bensenville",
                "Region" : "Illinois",
                "PostalCode" : "60106",
                "Country" : "United States"
            },
            "Home" : {
                "POBox" : "4315",
                "Locality" : "Bensenville",
                "Region" : "Illinois",
                "PostalCode" : "60106",
                "Country" : "United States"
            }
        },

        "Phone" : {
            "Home" : "555-555-1234",
            "Work" : "555-555-5678",
            "Mobile*" : "555-555-9090"
        },

        "Anniversary" : "20001004",
        "Birthday" : "19900415",
        "Email" : {
            "Work" : "rbrannan@contoso.com"
        },

        "Organization" : {
            "Name" : "Acme Widgets, Inc.",
            "Units" : [ "Administration" "Finance" ]
        },

        "Title" : "Chief Financial Officer",

        "Categories" : [ "Executive" ],

        "Website" : "https://www.example.com",

        "Photo" : {
            "MimeType" : "image/png",
            "Data" : "iBL{Q4GJ0x0000DNk~Le0000A0000A2nGNE0F5%wy#N3J1am@3R0s$N2z&@+hyVZp7)eAyR2Y?G{Qv*|e+D7|6ETWL6;e+j0BM>85Q>cpXaE2J07*qoM6N<$f&"
        },

        "Languages" : [ "en" ],
        
        "Notes" : "Hobbies: chainsaw carving, free climbing, underwater basket weaving"
    },

    "Secret" : {
        "Mensago" : {
            "Home" : {
                "Keys" : {
                    "encrypt" : {
                        "KeyHash" : "BLAKE2B-256:hf;9nd=_ucTPkRisv$!+^i1)A#WLUr09ji3p72E(",
                        "Value" : "CURVE25519:!u>#AhMqIC!?b5>LZwl}Vf{Aw2?+`>cMK@OFzEGp"
                    },
                    "verify" : {
                        "KeyHash" : "BLAKE2B-256:u<!zJ3~z%ByZ<1Cdb$Rr|0YNTfs8YD2Bc`S`KH5_",
                        "Value" : "ED25519:#J7q3bWP0z4(!WD3anbpY;~X|4=kp?PGg8ODEVhD"
                    }
                }
            }
        },
    }
}
----

== Field Definitions

Each of the fields defined in a contact are described below. Unless otherwise indicated, each field is assigned to the privacy group `private`. Most of these fields map directly to those found in the https://tools.ietf.org/html/rfc6350[vCard standard]. However, unlike the vCard standard, almost every field is optional so that a Mensago workspace account can be maintained with the only identifying information for the account being its numeric address. However, in the interest of cataloguing information for contacts who do not have a Mensago address, even this field is not required.

Header:Version:: REQUIRED. API version of the payload.

Header:EntityType:: REQUIRED. `EntityType` maps to the vCard field `KIND`. Values are `group`, `individual` (the default), or `org`. The `Member` field (listed below) is required for the `org` type and optional for `group`.

Header:Source:: REQUIRED. This field denotes the origin of the information. `owner` means that the information is updated by the entity itself – updates from the entity are sent to keep this information current. `client` means that the user’s client, not the owner, maintains this information. More information about this field and how the mechanism works can be found in the section _Updates and Client-Side Annotations_.

Header:Update:: CONDITIONAL. Describes whether or not the information in the contact is intended to update existing information and contains either the value 'no' or 'yes'. This payload field is REQUIRED in contact information update messages, but it is not present in other uses of the contact data.

FormattedName:: OPTIONAL. Privacy level `public`. `Formatted` maps to the vCard field `FN`. This field is the full formatted version of the entity’s name, including prefixes and suffixes.

Nicknames:: OPTIONAL. `Nicknames` maps to the vCard field `NICKNAME`.

GivenName:: OPTIONAL. Privacy level `public`. The primary name for an entity. In many cultures, this is an individual’s first name.

FamilyName:: OPTIONAL. Privacy level `public`. The family name for an entity.

AdditionalNames:: OPTIONAL. A list of additional names for the entity. In English-speaking countries, this is generally an individual’s middle name(s) or initial.

Prefixes:: OPTIONAL. Privacy level `public`. A list of prefix for an entity. For individuals in the United States, this translates to "Dr", "Mr", "Miss", etc.

Suffixes:: OPTIONAL. Privacy level `public`. A list of suffixes for an entity, such as "Esq." or "MD".

Gender:: OPTIONAL. Privacy level `public`. `Gender` maps to the vCard `GENDER` field’s gender identity component, which is a free-form text field.

MailingAddresses:: OPTIONAL. This is a dictionary of dictionaries containing mailing address information. The label applied to each sub-dictionary indicates the type of address described, such as 'Home' or 'Work'. The fields used largely map to corresponding parameters of the vCard field `ADR`. The mappings of these fields are explained in relation to U.S. mailing addresses merely for the sake of clarity. `POBox` is for postal office boxes. `StreetAddress` contains the street address. Apartment or suite numbers should use `ExtendedAddress` and not be included in `StreetAddress`. When in doubt, consult the postal organization for a particular country for how these two fields should be used. `Locality`, `Region`, and `PostalCode` map to the city, state, and ZIP code for a U.S. address. `Country` is used for the country for an address.

Phone:: OPTIONAL. This field contains key-value pairs of phone numbers and their labels, such as "Fax" or "Mobile". Note that the vCard field `TEL` roughly maps to this, as the names of the phone numbers are not rigidly defined, unlike the types in the vCard standard. An asterisk (’*’) MAY be appended to the value of the key to indicate the preferred contact number.

Mensago:: OPTIONAL. This field contains a list of field groups containing the components of each the contact’s Mensago addresses. The `Mensago` field itself is not required, but if it is present, all of its subfields are required to be present except possibly the `UserID` field.

Mensago:UserID:: OPTIONAL. This field contains the 'friendly' part of the contact's address. `Workspace` contains the UUID numeric identifier used for the entity’s account. If `UserID` is empty or missing, the client MUST use the contact's workspace address, e.g. `cavsfan4life/example.com` or `5ccc9ba6-9d4e-47d0-9c57-11ade969a88b/example.com`. 

Mensago:Domain:: CONDITIONAL. `Domain` contains the fully-qualified domain of the contact's address. 

Mensago:Keys:: CONDITIONAL. Privacy level `secret`. This field group sublist contains the contact’s Mensago cryptographic keys. Each key is named by its purpose. These are currently `verify`, `encrypt`, `social`, or `broadcast`. It is a required part of the `Mensago` field group. Handling for this field and its subfields is different from all others in this specification in that Mensago cryptographic keys MUST NOT exist in any other privacy group. These keys are automatically managed by client software and sent during the appropriate times during Contact Requests and contact information updates. Client software should generate a key set unique to each contact.

Mensago:Keys:KeyHash:: CONDITIONAL. This field contains the hash of the encryption key. The hash is Base85-encoded and prefixed by the hashing algorithm. It is a required part of the `Mensago` field group.

Mensago:Keys:Value:: CONDITIONAL. This field contains the actual encryption key data. For public-key encryption, this is the contact’s public key in CryptoString format.

Anniversary:: OPTIONAL. `Anniversary` maps to the vCard field `ANNIVERSARY`. This is the date of marriage or equivalent for the entity. Format is YYYYMMDD or MMDD.

Birthday:: OPTIONAL. `Birthday` maps to the vCard field `BDAY`. The birth date of the entity. Format is YYYYMMDD or MMDD.

Email:: OPTIONAL. This field contains a list of field groups containing a label for  the e-mail address and the address itself. Each entry in `Email` maps to an individual vCard `EMAIL` field. An asterisk (’*’) MAY be appended to the `Label` value to indicate the preferred contact address.

Organization:: OPTIONAL. `Organization` maps to the vCard `ORG` field. The field contains a list of strings denoting the levels of the units within the organization.

Title:: OPTIONAL. `Title` maps to the vCard `TITLE` field. It contains the title or job position of the entity.

Categories:: OPTIONAL. `Categories` maps to the vCard `CATEGORIES` field. It contains a list of string values for tags to apply to the entity.

Website:: OPTIONAL. `Website` specifies the URL of a website for the entity and maps to the vCard field `WEBSITE`.

Photo:: OPTIONAL. A field group containing photo information for the contact. The `Photo` field is not required, but if present, all of its subfields MUST be present.

Photo:Mime:: CONDITIONAL. This field contains the MIME type of the data stored in the `Data` field. Mensago clients MUST support `image/webp`, `image/png`, and `image/jpg` display. Because of the flexibility, quality, and smaller sizes of the format, WEBP images should be preferred. Support for other formats is optional. Support for animated profile photos is discouraged.

Photo:Data:: CONDITIONAL. This field contains Base85-encoded file data for the photo. The data in this field MUST be no larger than 500KiB before encoding is applied.

Languages:: OPTIONAL. `Languages` roughly maps to the vCard `LANG` field. It is a list of languages used in communications with the entity. The languages are listed in order of preference from most preferred to least. The codes themselves MUST follow the format established in the https://en.wikipedia.org/wiki/ISO_639-3[ISO 639-3] standard.

Notes:: OPTIONAL. Contains miscellaneous text notes stored in SFTM format. This field MUST NOT contain any attachment-type data, such as pictures or other kinds of files, but it MAY contain any other kind of SFTM-permitted data, such as links or tables. Attachment data MUST use the `Attachments` field described below.

Attachments:: OPTIONAL. This list of field groups contains miscellaneous data intended to be associated with the entity. Although this field is not required, each field group is required to have all fields populated and valid.

Attachments:Name:: CONDITIONAL. It contains the name of the attached data. This name can be a file name, but is not required to be.

Attachments:Mime:: CONDITIONAL. It contains the MIME type of the encoded data.

Attachments:Data:: CONDITIONAL. It contains the actual Base85-encoded data of the attachment.

== Updates and Client-Side Annotations

Mensago contact information is designed from the outset to always be up-to-date and places the responsibility on the information owner to keep it that way. This does, however, present a problem when the contact information is not complete or the user wishes to keep personal notes related to the contact. The solution lies in an information overlay accomplished through an additional information group, "Annotations". In addition to the header and three Privacy Groups, a contact’s entry may contain a fifth group which is applied first and overridden by information in the three Privacy Groups. Take the following example:

[source,json]
----
{
    "Header" : {
        "Version" : "1.0",
        "EntityType" : "individual",
        "Source" : "owner",
    },
    "Public" : {
        "GivenName" : "Fred",
        "FamilyName" : "Kingsley",
        "Gender" : "male",
        "Mensago" : {
            "Home" : {
                "UserID" : "fkingsley",
                "Workspace" : "3f258107-19aa-43c1-86c6-30e3914e18b8",
                "Domain" : "example.com",
            }
        },
    },
    "Private" : {
        "Birthday" : "19860314",
    },
    "Secret" : {
        "Mensago" : {
            "Home" : {
                "Keys" : {
                    "Verify" : {
                        "KeyHash" : "BLAKE2B-256:#ksGJdu4{=P3@UdZ787UB>kZ%S4bze?G?9uhF4fo",
                        "Value" : "ED25519:te#3G{*qG&_rK<Pfd6EWVeU_$){-Wxh|&+Gj)S<G"
                    },
                    "Encrypt" : {
                        "KeyHash" : "BLAKE2B-256:)}sRcq+f=Kyx2tg03mPbIq`>_u!ha4*pa0n$u!)v",
                        "Value" : "CURVE25519:)r)+9^WCSo!5s~9ru~Vy0`CcP$|Cees`oh9+I6ZT"
                    }
                }
            }
        },
    },
    "Annotations" : {
        "Phone" : { "Mobile" : "555-345-1543" },
        "Birthday" : "0314"
    }
}
----

In the above example, the contact has provided a number of fields. The user has filled in information related to the contact's mobile phone number and birth month and year. When the client works with the contact's data, it will display the full birthdate provided by the contact, but it will display the mobile phone number entered by the user. Annotations give the user the ability to "fill in the holes" while also ensuring that a contact is the authority on their own information.

Information updates are sent whenever users update their contact information. These updates only send the changes. Fields which are deleted are sent with empty data. Updates cannot affect annotations, but if a contact deletes a field in an update, it may result in an annotation being displayed when it previously was not.

== Contact Requests

Unlike e-mail, communication with other users on the Mensago platform is on an opt-in basis. A Contact Request exchange similar to those found on social media must take place before any sort of communication can take place between two entities. The result is a simple, familiar concept which places users in control and provides a means to exchange encryption keys. Filtering and organizing communications is part of the design of the platform.

The Contact Request process is as follows:

[arabic]
. User #1 retrieves and validates User #2’s keycard. The keycard for User #2 contains an encryption key used to encrypt the contact request. More information on this process and keycards in general can be found in the Keycard Specification.
. User #1 sends a request to User #2. This request contains whatever contact information User #1 wishes to share (name, address, etc.) in the form of a <<pips,Personal Information Profile>> (PIP). It is signed by User #1’s request signing key so that User #2 can verify that the request actually came from User #1 and encrypted with User #2’s request encryption key so that no one except User #2 can read it. Once received, User #2 can determine if contact should be permitted. More information on PIPs can be found in the <<pips,section further below>>.
. User #2 may drop the request and optionally block future requests. If User #2 approves the request, an encrypted response is sent with User #2’s PIP. Unlike the initial request, the acceptance message contains
the full information provided in the PIP provided by User #2.
. User #1 receives the approval and is asked to share his/her personal information with User #2. How much information is shared is up to User #1. This response also includes public keys for both encryption and signing which are unique to that contact.

This process enables exchange of information without exposure to infrastructure and a minimum of back-and-forth to enable the information exchange. The combination of contact requests and required encryption enables several security advantages:

* Encryption can be computationally expensive, which makes mass messaging harder to hide on a compromised machine and slows throughput without placing undue hardships on individuals sending a message to a few friends.
* Phishing is much more difficult because the sender’s identity is required and each contact's keypairs are unique.
* Only contact requests may be sent to the user with their contact request key. Other types of messages encrypted with it are silently dropped.
* Because the sender's verifiable identity is required, spamming people through the contact request mechanism is easily stopped.

The Contact Request process is unique in that it is the only type of message that can be sent to a recipient without any prior contact having been made. As such, it is very strictly regulated. For example, not only are file attachments of any type not part of the specific format used for Contact Requests, they are **utterly forbidden**. Clients which encounter a Contact Request message with any type of attachment MUST silently drop it. Users can -- and should -- be reported for sending spam via Contact Requests. Administrators are highly encouraged to suspend and/or terminate accounts which exhibit this behavior. 

*Contact Request: Stage 1 (Lookup)*

Initiated by a client when a user requests contact with another user. The client requests and resolves the other user’s keycard.

*Contact Request: Stage 2 (Initiation)*

Sent after the potential contact’s request key has been received. The client is not required to provide any more personal information than that which is already available in the user’s keycard. However, users are encouraged to share additional information to help the recipient validate who the sender is. With the exception of encryption keys, any field found in the Contacts Specification can be found as part the contact request payload. A sample payload is shown below.

[source,json]
----
{
    "Type" : "sysmessage",
    "Subtype" : "contactreq.1",
    "Version" : "1.0",
    "From" : "3cb11ab3-5482-4154-8ca1-dfa1cc79371c/contoso.com",
    "To" : "662679bd-3611-4d5e-a570-52812bdcc6f3/mensago-example.com",
    "Date" : "20190905T155323Z",
    "Privacy" : "Public",
    "EntityType" : "individual",
    "Name" : {
        "Given" : "Richard",
        "Family" : "Brannan",
    },
    "Gender" : "Male",
}
----

*Contact Request: Stage 3 (Response)*

Sent by a contact request recipient to approve a contact request. Should the recipient approve the request, the approval message is sent with the recipient’s contact information along with encryption and verification keys to be used when contacting the user. Unlike the sender’s initial request, this response contains all of the contact information which the recipient intends to share with the sender. This payload uses the subtype `contactreq.2`. A recipient can report a contact request to the Abuse address at the server of the sender’s organization.

*Contact Request: Stage 4 (Acknowledgement)*

Sent by the initial contact request sender to fill in any information not initially sent. Additional personal information is not required for the acknowledgement, but this extra step enables a sender to share enough information to be identified by the recipient in the initial message without sending potentially sensitive information to the wrong person. This payload uses the subtype `contactreq.3`. Note that the information sent in this message is supplemental to that sent in the initial request. The recipient’s address book information is updated when this message is received. When this message is sent, the client application should make a note of what information profile was used for future change updates.

*Contact Information Update*

Sent by a user to notify contacts of a change in contact information. The payload sent uses the subtype ` `contactupdate`. The fields and structure are exactly the same as the contact requests, but the update
message is encrypted with the user's regular contact key created for that recipient, not the recipient’s contact request key. Empty fields which are sent are intended to delete information which was previously available. Note that any client-side annotations made by the recipients to the sender’s contact information are retained, but the information provided by the sender is not.
