= Mensago Platform Overview
:author: Jon Yoder
:email: jon@yoder.cloud
:revdate: 2021-10-25
:revnumber: 1.0
:description: Overview of the Mensago platform
:keywords: Mensago, overview, cryptostring, security
:toc: preamble
:table-stripes: odd

*Status:* Draft (incomplete) +

== Introduction

Mensago is an online communications platform intended to replace e-mail in its current form and cohesively add groupware features. The mission of Mensago is to provide to people the ability to connect with one another and organize their lives with privacy-respecting digital tools. The principles used to guide the decision-making process for the Mensago platform are as follows:

* Server has near-zero knowledge of user data
* Compatibility with other standards where possible
* Complexity is a burden
* Utilize proven technologies and adapt concepts from others
* Openness
** Open standard - documented and unencumbered by patents or IP
** Open source - reference implementation licensed for any purpose
** Open federation - anyone can run a server

Functionality that the Mensago platform provides:

* Storage and synchronization of encrypted data
* Message delivery
* Message flow control, both inbound and outbound

== Terminology

workspace:: a data container which comes in two types: individual and shared. Individual workspaces are tied to a user's identity. Shared workspaces are spaces for collaboration.

workspace ID:: a universally-unique identifier (UUID) which is the public representation of a specific workspace.

workspace address:: a workspace ID combined with its associated domain and separated by a forward slash, similar to an IP address for a device on a network. Example: `301fa6cf-ce2d-4349-8d5b-4053b1808489/example.com`.

Mensago address:: an optional public-facing name tied to a workspace ID intended for everyday usage, similar to a domain name assigned to an IP address on the Internet. Example: `Se単orJones/example.com`

user ID:: the optional human-friendly part of a Mensago address. Example: `Se単orJones` in `Se単orJones/example.com`.

keycard:: a digital certificate representing a person or organization that contains encryption keys and public information in a cryptographically secure and verifiable form.

client file:: a server-side file containing JSON-structured Mensago data. It consists of a header, an encrypted payload, and some minimal metadata. Each client file represents a corresponding file on the user's device.

== Architecture

Electronic mail is a federated system in which messages are delivered from one carrier to another until it has been transported from the sender to the recipient. It is unlike instant messaging in that each message is a self-contained unit sent one-way; there is no dialog between sender and recipient involved in the delivery of that one message. This creates its own set of challenges.

Mensago is built such that the server is little more than a file synchronization and message delivery service; most of the real work is handled by client applications. This has many benefits, but the main two are offloading CPU-intensive encryption processes to the client and minimizing the knowledge a server has about client data.

One major departure from traditional e-mail is that messages are not just for user communications. Because each message is encrypted, potentially sensitive information can be sent without concern, and Mensago clients send messages intended for others' client software. These system-level messages are used to perform platform-level tasks, such as support requests for the provider or contact information updates.

=== CryptoString

One of the many challenges with working with encryption is that keys and hashes are arbitrary-looking binary blobs of data -- they have zero meaning to people just looking at them. They also lack context or any other descriptive information; a 256-bit BLAKE2B hash looks the same as a SHA256 hash, but Heaven help you if you get something mixed up.

The solution is to represent keys and hashes as text and pair an algorithm nametag with the text representation of the key or hash. For example, a sample 128-bit BLAKE2B hash in its binary form is represented in hex as `a6 30 2a b0 da ef 14 fb 9b 82 b9 69 3e 78 76 6b`. Without spaces, this is 32 characters. The same hash can be represented in CryptoString format as `BLAKE2B-128:rZ6h7+V2$mn}WG%K6rL(`.

The format consists of the prefix, a colon for the separator, and the Base85-encoded binary data. Base85 was chosen because of its higher efficiency and source. The prefix consists of up to 24 characters, which may be capital ASCII letters, numbers, or dashes. A colon is used to separate the prefix from the encoded data.

The official prefixes as of this writing are:

- ED25519
- CURVE25519
- AES-128 / AES-256 / AES-384 / AES-512
- SALSA20 / XSALSA20
- SHA-256 / SHA-384 / SHA-512
- SHA3-256 / SHA3-384 / SHA3-512
- BLAKE2B-128 / BLAKE2B-256 / BLAKE2B-512
- BLAKE3-128 / BLAKE3-256 / BLAKE3-512

=== Workspaces, Users, and Identity

Workspaces are the central concept of the platform. Similar to mailboxes, they store user data, but the files themselves can be of different types, including tasks, messages, files, and calendar events. Workspaces have one of two types: individual and shared. Identity is linked to individual workspaces. Shared workspaces are spaces for collaboration. Instead of providing identity, a permissions system determines what actions members may take and which folders they may access.

Each workspace is tied to an ID and a domain. The ID itself is just a Universally Unique Identifier which exists to differentiate one workspace from another--it has no other significance. It is randomly generated when the workspace is created, never changes, and for security reasons, is never reused. A workspace address is a combination of this ID and its domain, separated by a slash. A slash is used to ensure that both workspace address and the person-friendly Mensago address, described below, are never confused with an e-mail address. Workspace IDs are unique to a server. 

A User ID can optionally be associated with a workspace. User IDs are much easier to exchange and are internationalization-friendly. Capitalization does not matter, and whitespace is restricted. User IDs may be up to 32 UTF-8 code points long. Example: `Se単orJones/example.com` Although many different other characters may be used as part of a User ID, such as emoji, it is not recommended. The User ID's `admin`, `abuse`, and `support` are reserved and may not be used except by administrators.

A folder hierarchy defines locations for different types of data within the workspace. Folders within a workspace use UUIDs for their names on the server side, making them uniquely identifiable while giving no clues to their contents. The data files in each folder are also named to be as generic as possible -- utilizing a UUID, a timestamp, and their file size so that quotas can be quickly calculated. Each "application" on the platform, such as calendars or address books, have their own folder for their data.

Concerning formatting, UUIDs, user IDs, domains, and addresses in general are required to be internally stored as all lowercase, but user-facing representations may also use capitals. For consistency and readability, UUIDs MUST be formatted in the 36-character format with dashes, e.g. `1188e93f-2ae2-4aea-95fe-4a9e70644d86`.

=== Devices

A device is merely an access method to a Mensago server. Each user has a list of associated devices for his/her workspace, each identified by a UUID and its own asymmetric encryption key. Each application may utilize its own device ID. Thus, an Android phone with separate applications for accessing calendar, contacts, messages, notes, and tasks could have 6 different device IDs whereas a desktop PC running an all-in-one client could just have one. For maximum compatibility, there are defined locations for client-side user data.

== Versioning

API versions take the form of X.Y.Z: X is major version, Y is minor version, Z is patch level.

* Major version changes indicate breaking changes in the API -- a client running 2.5.1 will need source code changes in order to be compatible with version 3.0.0.
* Minor version changes are for adjustments in an individual API, such as for tasks. Potential breaking changes may or may not be included in minor version changes, but such changes should require only minor adjustments.
* Patch level changes are backwards-compatible API changes.

== License

The Mensago specification is distributed under the Creative Commons CC-BY-SA license unless otherwise noted.

== Security and Threat Modeling

As a platform, Mensago places minimum trust in infrastructure, plans for compromise, and expects bad behavior.

=== Server

A Mensago server is intended to act as an verifying third party for identity services and to provide message delivery and device synchronization. It also provides facilities to protect the organization from bad behavior.

==== Spam

Depending on the sources consulted, a large percentage of all e-mail sent is spam, which for the purposes of this project, is defined as unsolicited commercial e-mail. It could be something as simple as a pharmaceutical-related messages from an unreputable source. The Mensago definition of spam also includes communications like unwanted newsletters sent by a legitimate business. Many online vendors use dark patterns to trick users into signing up for a mailing list for their products or simply skip to the end and automatically sign all customers up. Although less malicious, junk e-mail is a major productivity sink because it adds to the clutter a person must deal with. More technical users can manage e-mail subscriptions, but less-savvy users don't know how and don't learn how for a variety of reasons. These users are essentially trapped. This is completely unacceptable.

Spam e-mail is enabled by several different factors:

- A message can be sent to anyone without their consent
- Limitations on traffic volume are a function of server product features and administrator configuration
- Protocols place no limits on the number of recipients a message may have

To eliminate spam, the following provisions have been made:

- All contact is opt-in, giving users control over who can send them messages
- The protocol allows an individual to send a message to up to 25 recipients. Larger groups of people require use of a shared workspace.
- Server software is required to have traffic controls in place for all workspaces
- Users can utilize the built-in abuse reporting mechanisms to report spammers their administrator
- Administrators can block domains reported to have bad behavior.
- Administrators have an incentive to police their users to that the entire domain doesn't get blocked by other instances.
- Contact requests are the only kind of unsolicited message permitted to be sent, and client software is required to strip embedded links and images from any requests received. Client software is also expected to be engineered to prevent users from sending contact requests with links or images.
- Client software can enable users to automatically block contact requests from specific users or entire domains.

