= Mensago Messaging Specification
Jon Yoder <jsyoder@mailfence.com>
v1.1, 2021-05-01

*Status:* Draft +
*Abstract:* Mensago message structure

== Description

The reason for Mensago’ existence is to replace e-mail with a secure, private, and otherwise better technology. Messages are long-form text communications which can be divided into two classes: system messages and user messages. User messages are just that: communications written by users to be sent to other users. System messages, on the other hand, are for communications management. This specification describes messaging workflows and the payload portion of a client file which is used for messaging. The wrapper information for the client file, i.e. encryption type, recipient address, etc., is described in the Mensago Client-Server API specification.

== Encryption Keys

Each Mensago workspace uses multiple encryption keys. Two of the reasons for this are flexibility and security: concerns are better separated and if a key should be compromised, it is far easier to update the one key for one component of the system than to update all of them.

*Message Encryption/Signing Keys* : Each contact in a workspace's address book is assigned its own unique keypairs which are used for signing and encrypting messages, preventing contacts from sharing keys. 

*Contact Request Encryption Key* : This asymmetric keypair is only used for contact requests. The public half of this key and the public half of the user's Contact Request Signing Key (below) are published the user’s keycard and are easily-accessible public information, unlike all of a workspace's other encryption and signing keys.

*Contact Request Signing Key* : This asymmetric keypair is for signing contact requests before they are encrypted.

*Broadcast Key* : This key is a symmetric key used for group messaging. The encryption standard may vary, but as of this writing, there are several supported standards: XChaCha20, ChaCha20, AES128, and AES256.
Because this key can potentially be given out to large numbers of recipients, a workspace may have multiple broadcast keys.

*System Key*: Another symmetric key, the system key is used for encrypting system messages. Users never directly interact with this key.

*Social Key*: This symmetric key will be used specifically for the Terrazzo social networking module. This key type may also have multiple keys.

*Storage Key*: This symmetric key is used to encrypt client files for storage and synchronization on the server.

*Key Request Key* : This one-time-use asymmetric key is generated when encryption keys are requested for the first of a user’s devices to access a shared workspace. It is discarded after the encryption keys for
a shared workspace have been obtained.

== Payload Structures

Every user file on a Mensago server is stored in encrypted form. All binary data is Base85-encoded so that it is human-readable at a basic level in the event of the need for an administrator's intervention. Listed below is a sample of the contents of one of these files.

[source]
----
MENSAGO
{
    "Version": "1.0",
    "Receiver": "G!$Rod&LyJ6-yNaemQ?i`l&*|{V&aco)IUNj!RuS3VbAVQ5@BFu!lQDF+6&n>Zjm7h6#cL<jct?4uqj@#SYJ=n3@GqIuXvwJyfK>$uQ}u%kTd_L?rC1uNRLe0@<is)NRiCl?Ws;EI!0}a}H1c!-Z}lLp@SBdiAEK>86z",
    "Sender": "65}GwUkZNN42t=#`4wj4V~Z~ND97KHB1pnvzmpwUgcjANT>3_j9+}!u)pvsgD07Sr3EC@K$~hc&(jpsJQ|}eT8=N7`t$}KgF9qi~dDVA{5W^uq9zx_LR$KKseCbt4_y6Lqj6xAQfK^jjrS;Cx4~mLV<mnnjk*cY*!W$ZaGTfo&",
    "Date": "20190905 155323",
    "KeyHash": "BLAKE2B-256:cy)wynX>FX1!`%3rR}t1ILJTtM*q)|cI_^ycs9D?",
    "PayloadKey": "2Iuql{B^xtCES?}`Sy-o-z##Jzo&blqkQMk_Vg@yrNal66#^p2X9waP??5078`D#ab*_n4sNR1glHWqEaf_wQ53z~vRl1o<?JaRMugPL#gjI)<sAv6DTm_@6^#"
}
----------
XSALSA20
Out!JUOZxWzT9FMtl@QKpJH4;jPOT>16T0I(-53YFi~@mT|zBb`dC8ZmyYw&wL3fVjAB6F3GyL<KxMj0tW23agZPJRzosYY_jO$Q(w+mq6fOu9T%9=OB8#BGEJ+mpg&)4`i<K)!PSS`(-xmDfMD<e44%P-fbPHDhQtt+xW#p*JX_ZT&jX~M*-62-aD?r>ye=HonJ*-C1edIoZ>XJb9cFrN`8e@3|`UV1v{{i60Z{gY(UlT)k-u)csnX-S4Gph=XC3o>}mGQzaKx&Wt&XJsJr9D`U%uQ0;D6@R|ZJ8Ag^)*OG3nB&~k#pi;)_pXh_J8&)Al$G`;evJ*ViFas&P%Z8nAR0#s6r1Ubj#wo{m+S*4g9CZpGZlU+-!5;Hg3fEj>(;i(sNVDDGlKfMWS1=IJkXp)JR9SdHb7*>`;y;qwlp~C%L;vcuE^(<ad^G{-)cS
----

It is immediately obvious that very little useful data can be gleaned from the contents of one of these files. This is by design. It is impossible for a malicious actor who has compromised the sending or receiving server to immediately discern anything. If the actor were able to access the private key for the server, they could decrypt the `Recipient` field for incoming messages and the `Sender` field for outgoing messages. Both fields could be decrypted for messages which were sent and received by users within the organization. The only information gained would be sender and recipient information and timestamps of the messages.

When fully decrypted, the message envelope information would look like this:

[source,json]
----
{
  "Version": "1.0",
  "Receiver": {
    "To": "22222222-2222-2222-2222-222222222222/example.com",
    "SenderDomain": "example.com"
  },
  "Sender": {
    "From": "11111111-1111-1111-1111-111111111111/example.com",
    "RecipientDomain": "example.com"
  },
  "Date": "20190905 155323",
}
----

The `PayloadKey` field would just contain a 32-byte blob of binary data that was used for the encryption key. The payload, which was kept separate in the file, would look like this:

[source,json]
----
{
  "Type": "usermessage",
  "Version": "1.0",
  "From": "11111111-1111-1111-1111-111111111111/example.com",
  "To": "22222222-2222-2222-2222-222222222222/example.com",
  "Date": "20190905 155323",
  "ThreadID": "2280c1f2-d9c0-440c-a182-967b16ba428a",
  "Subject": "Sample User Message",
  "Body": "It was a bright cold day in April, and the clocks were striking thirteen."
}
----

*User Message Fields*

_Type_ - REQUIRED. This field is required for all payloads. It defines the type of payload.

_Version_ - REQUIRED. This field is required for all payloads. In this case it contains the messaging API version.

_From_ - REQUIRED. The workspace address of the sender.

_To_ - REQUIRED. The workspace address of the recipient. This field MUST contain only one address. If a message is sent to multiple recipients, the others must be indicated in the `CC` or `BCC` fields. At no time should this field contain a Mensago address, such as _CatsR4Evar/example.com_

_CC_ - OPTIONAL. A list of other recipients. Like the `To` field, this MUST contain only workspace addresses. Each recipient in this field will be able to see the workspace addresses of other recipients in this field.

_BCC_ - OPTIONAL. A list of workspace addresses of any blind carbon-copied recipients. Recipients in this field will not see the addresses of any other recipients in their copy of the message. Like the `To` field, this MUST contain only workspace addresses.

_Date_ - REQUIRED. The UTC date and time when the message was sent in the format `YYMMDD HHMMSS`.

_ThreadID_ - REQUIRED. A UUID is used to represent the conversation ID.

_Subject_ - REQUIRED. A string up to 100 characters in length. The characters MUST be valid printable UTF-8 characters or a space. Note that while the field itself is required, the field itself MAY be empty.

_Body_ - REQUIRED. A string of UTF-8 characters of any length. Escapement of content for JSON compliance is required.

_Attachments_ - OPTIONAL. A list of dictionaries containing attached data. Attachment format is listed below.

*Attachment Fields*

_Name_ - REQUIRED. The name of the attached file.

_Type_ - REQUIRED. The MIME type of the attached file.

_Data_ - REQUIRED. The Base85-encoded data.

== System Messages

System messages are not sent directly to a user. Instead, they facilitate communications and protocol state and are encrypted unless stated otherwise. Aside from those directly-related to messaging, system messages are defined in the specification to which they are related.

All system messages are required to have the type `sysmessage` and also have a `Subtype` field, which indicates the type of system message. The schema for a system message is defined based on the `Type`, `Subtype`, and `Version` fields.

*Abuse Report*

Abuse reports are sent to the address specified in the organization’s keycard, or if not specified, the Admin address. It is structurally similar to a standard user message except that the subtype is `abusereport` and the subject MUST be the numeric address of the offender. The body of the message MUST contain the description of the abuse report. The submitter MAY attach a sample of the message to the
administrator, if need be.

[source,json]
----
{
    "Type" : "sysmessage",
    "Subtype" : "abusereport",
    "Version" : "1.0",
    "From" : "3cb11ab3-5482-4154-8ca1-dfa1cc79371c/contoso.com",
    "To" : "662679bd-3611-4d5e-a570-52812bdcc6f3/mensago-example.com",
    "Date" : "20190905 155323",
    "ThreadID" : "8e24ab6b-b466-492b-a3b1-4ce736a59563",
    "Subject" : "df7c310a-b947-4f9d-a66b-600d5fdd7e0c/mensago-example.com",
    "Body" : "This user purposely sent me malware which raised my insurance rates by 15%.",
}
----

*Support Request*

Support requests are sent to the address specified in the organization’s keycard, or if not specified, the required Admin address. Like an abuse report, a support request is structurally similar to a standard user
message except that the subtype is `supportrequest`. The subject MUST contain a summary of the problem, and the body of the message MUST contain the description of the problem experienced by the submitter. Note that administrators are well within their rights to mute users who abuse the support request system, and service providers are not restricted from charging users for support.

[source,json]
----
{
    "Type" : "sysmessage",
    "Subtype" : "supportrequest",
    "Version" : "1.0",
    "From" : "3cb11ab3-5482-4154-8ca1-dfa1cc79371c/contoso.com",
    "To" : "662679bd-3611-4d5e-a570-52812bdcc6f3/mensago-example.com",
    "Date" : "20190905 155323",
    "ThreadID" : "8e24ab6b-b466-492b-a3b1-4ce736a59563",
    "Subject" : "I can't find the Any key",
    "Body" : "Connect tells me to press Any key, but I can't find it on my keyboard anywhere!",
}
----
