= Mensago Messaging Specification
Jon Yoder <jsyoder@mailfence.com>
v1.0, 2019-09-06

*Status:* Draft +
*Abstract:* Mensago message structure

== Description

The reason for Mensago’ existence is to replace e-mail with a secure, private, and otherwise better technology. Messages are long-form text communications which can be divided into two classes: system messages and user messages. User messages are just that: communications written by users to be sent to other users. System messages, on the other hand, are for communications management. This specification describes messaging workflows and the payload portion of a client item which is used for messaging. The wrapper information for the client item, i.e. encryption type, recipient address, etc., is described in the Mensago Client-Server API specification.

== Encryption Keys

Each Mensago workspace uses multiple encryption keys. Two of the reasons for this are flexibility and security: concerns are better separated and if a key should be compromised, it is far easier to update the one key for one component of the system than to update all of them.

*Message Encryption/Signing Keys* : Each contact in a workspace's address book is assigned its own unique keypairs which are used for signing and encrypting messages, preventing contacts from sharing keys. 

*Contact Request Encryption Key* : This asymmetric keypair is only used for contact requests. The public half of this key and the public half of the user's Contact Request Signing Key (below) are published the user’s keycard and are easily-accessible public information, unlike all of a workspace's other encryption and signing keys.

*Contact Request Signing Key* : This asymmetric keypair is for signing contact requests before they are encrypted.

*Broadcast Key* : This key is a symmetric key used for group messaging. The encryption standard may vary, but as of this writing, there are several supported standards: XChaCha20, ChaCha20, AES128, and AES256.
Because this key can potentially be given out to large numbers of recipients, a workspace may have multiple broadcast keys.

*System Key*: Another symmetric key, the system key is used for encrypting system messages. Users never directly interact with this key.

*Social Key*: This symmetric key will be used specifically for the Terrazzo social networking module. This key type may also have multiple keys.

*Storage Key*: This symmetric key is used to encrypt client items for storage and synchronization on the server.

*Key Request Key* : This one-time-use asymmetric key is generated when encryption keys are requested for the first of a user’s devices to access a shared workspace. It is discarded after the encryption keys for
a shared workspace have been obtained.

== Payload Structures

Every user file on a Mensago server is stored in encrypted form. All binary data is Base85-encoded so that it is human-readable at a basic level in the event of the need for an administrator's intervention. Listed below is a sample of the contents of one of these files.

[source]
----
MENSAGO
{
    "Version": "1.0",
    "Receiver": "G!$Rod&LyJ6-yNaemQ?i`l&*|{V&aco)IUNj!RuS3VbAVQ5@BFu!lQDF+6&n>Zjm7h6#cL<jct?4uqj@#SYJ=n3@GqIuXvwJyfK>$uQ}u%kTd_L?rC1uNRLe0@<is)NRiCl?Ws;EI!0}a}H1c!-Z}lLp@SBdiAEK>86z",
    "Sender": "65}GwUkZNN42t=#`4wj4V~Z~ND97KHB1pnvzmpwUgcjANT>3_j9+}!u)pvsgD07Sr3EC@K$~hc&(jpsJQ|}eT8=N7`t$}KgF9qi~dDVA{5W^uq9zx_LR$KKseCbt4_y6Lqj6xAQfK^jjrS;Cx4~mLV<mnnjk*cY*!W$ZaGTfo&",
    "Date": "20190905 155323",
    "KeyHash": "BLAKE2B-256:cy)wynX>FX1!`%3rR}t1ILJTtM*q)|cI_^ycs9D?",
    "PayloadKey": "2Iuql{B^xtCES?}`Sy-o-z##Jzo&blqkQMk_Vg@yrNal66#^p2X9waP??5078`D#ab*_n4sNR1glHWqEaf_wQ53z~vRl1o<?JaRMugPL#gjI)<sAv6DTm_@6^#"
}
----------
XSALSA20
Out!JUOZxWzT9FMtl@QKpJH4;jPOT>16T0I(-53YFi~@mT|zBb`dC8ZmyYw&wL3fVjAB6F3GyL<KxMj0tW23agZPJRzosYY_jO$Q(w+mq6fOu9T%9=OB8#BGEJ+mpg&)4`i<K)!PSS`(-xmDfMD<e44%P-fbPHDhQtt+xW#p*JX_ZT&jX~M*-62-aD?r>ye=HonJ*-C1edIoZ>XJb9cFrN`8e@3|`UV1v{{i60Z{gY(UlT)k-u)csnX-S4Gph=XC3o>}mGQzaKx&Wt&XJsJr9D`U%uQ0;D6@R|ZJ8Ag^)*OG3nB&~k#pi;)_pXh_J8&)Al$G`;evJ*ViFas&P%Z8nAR0#s6r1Ubj#wo{m+S*4g9CZpGZlU+-!5;Hg3fEj>(;i(sNVDDGlKfMWS1=IJkXp)JR9SdHb7*>`;y;qwlp~C%L;vcuE^(<ad^G{-)cS
----

It is immediately obvious that very little useful data can be gleaned from the contents of one of these files. This is by design. It is impossible for a malicious actor who has compromised the sending or receiving server to immediately discern anything. If the actor were able to access the private key for the server, they could decrypt the `Recipient` field for incoming messages and the `Sender` field for outgoing messages. Both fields could be decrypted for messages which were sent and received by users within the organization. The only information gained would be sender and recipient information and timestamps of the messages.

When fully decrypted, the message envelope information would look like this:

[source,json]
----
{
  "Version": "1.0",
  "Receiver": {
    "To": "22222222-2222-2222-2222-222222222222/example.com",
    "SenderDomain": "example.com"
  },
  "Sender": {
    "From": "11111111-1111-1111-1111-111111111111/example.com",
    "RecipientDomain": "example.com"
  },
  "Date": "20190905 155323",
}
----

The `PayloadKey` field would just contain a 32-byte blob of binary data that was used for the encryption key. The payload, which was kept separate in the file, would look like this:

[source,json]
----
{
  "Type:": "usermessage",
  "Version": "1.0",
  "From": "11111111-1111-1111-1111-111111111111/example.com",
  "To": "22222222-2222-2222-2222-222222222222/example.com",
  "Date": "20190905 155323",
  "ThreadID": "2280c1f2-d9c0-440c-a182-967b16ba428a",
  "Subject": "Sample User Message",
  "Body": "It was a bright cold day in April, and the clocks were striking thirteen."
}
----

*User Message Fields*

_Type_ - REQUIRED. This field is required for all payloads. It defines the type of payload.

_Version_ - REQUIRED. This field is required for all payloads. In this case it contains the messaging API version.

_From_ - REQUIRED. The numeric Mensago address of the sender.

_To_ - REQUIRED. The numeric Mensago address of the recipient.

_CC_ - OPTIONAL. A list of numeric Mensago addresses of any carbon-copied recipients.

_BCC_ - OPTIONAL. A list of numeric Mensago addresses of any blind carbon-copied recipients.

_Date_ - REQUIRED. The UTC date and time when the message was sent in the format `YYMMDD HHMMSS`.

_ThreadID_ - REQUIRED. A UUID is used to represent the conversation ID.

_Subject_ - REQUIRED. A string up to 100 characters in length. The characters MUST be valid printable UTF-8 characters or a space. Note that while the field itself is required, the field itself MAY be empty.

_Body_ - REQUIRED. A string of UTF-8 characters of any length. Escapement of content for JSON compliance is required.

_Attachments_ - OPTIONAL. A list of dictionaries containing attached data. Attachment format is listed below.

*Attachment Fields*

_Name_ - REQUIRED. The name of the attached file.

_Type_ - REQUIRED. The MIME type of the attached file.

_Data_ - REQUIRED. The Base85-encoded data.

== System Messages

System messages are not sent directly to a user. Instead, they facilitate communications and protocol state and are encrypted unless stated otherwise. Aside from those directly-related to messaging, system messages are defined in the specification to which they are related.

*Abuse Report*

Abuse reports are sent to the address specified in the organization’s keycard, or if not specified, the Admin address. It is structurally similar to a standard user message except that the subtype is `abusereport` and the subject MUST be the numeric address of the offender. The body of the message MUST contain the description of the abuse report. The submitter MAY attach a sample of the message to the
administrator, if need be.

[source,json]
----
{
    "Type" : "sysmessage",
    "Subtype" : "abusereport",
    "Version" : "1.0",
    "From" : "3cb11ab3-5482-4154-8ca1-dfa1cc79371c/contoso.com",
    "To" : [ "662679bd-3611-4d5e-a570-52812bdcc6f3/mensago-example.com" ],
    "Date" : "20190905 155323",
    "ThreadID" : "8e24ab6b-b466-492b-a3b1-4ce736a59563",
    "Subject" : "df7c310a-b947-4f9d-a66b-600d5fdd7e0c/mensago-example.com",
    "Body" : "This user purposely sent me malware which raised my insurance rates by 15%.",
}
----

*Support Request*

Support requests are sent to the address specified in the organization’s keycard, or if not specified, the required Admin address. Like an abuse report, a support request is structurally similar to a standard user
message except that the subtype is `supportrequest`. The subject MUST contain a summary of the problem, and the body of the message MUST contain the description of the problem experienced by the submitter. Note that administrators are well within their rights to mute users who abuse the support request system, and service providers are not restricted from charging users for support.

[source,json]
----
{
    "Type" : "sysmessage",
    "Subtype" : "supportrequest",
    "Version" : "1.0",
    "From" : "3cb11ab3-5482-4154-8ca1-dfa1cc79371c/contoso.com",
    "To" : [ "662679bd-3611-4d5e-a570-52812bdcc6f3/mensago-example.com" ],
    "Date" : "20190905 155323",
    "ThreadID" : "8e24ab6b-b466-492b-a3b1-4ce736a59563",
    "Subject" : "I can't find the Any key",
    "Body" : "Connect tells me to press Any key, but I can't find it on my keyboard anywhere!",
}
----

== Contact Requests

Unlike e-mail, communication with other users on the Mensago platform is on an opt-in basis. A contact request exchange similar to those found on social media must take place before any sort of communication can take place between two entities. The result is a simple, familiar concept which places users in control and provides a means to exchange encryption keys. Filtering and organizing communications is part of the
design of the platform.

The contact request process is as follows:

[arabic]
. User #1 retrieves and validates User #2’s keycard. The keycard request is sent both through the user’s server and from the user’s client itself to ensure no sneaky tricks by either server. The keycard for User #2 contains an encryption key used to encrypt the contact request. More information on keycards can be found in the link:/spec/keycard[Keycard Specification].
. User #1 sends a request to User #2. This request contains whatever contact information User #1 wishes to share (name, address, etc.) in the form of a Personal Information Profile (PIP). It is signed by User #1’s
request signing key so that User #2 can verify that the request actually came from User #1 and encrypted with User #2’s request encryption key so that no one except User #2 can read it. Once received, User #2 can
determine if contact should be permitted. More information on PIPs can be found in the link:/spec/contacts[Contacts Specification].
. User #2 may drop the request and optionally block future requests. If User #2 approves the request, an encrypted response is sent with User #2’s PIP. Unlike the initial request, the acceptance message contains
the full information provided in the PIP provided by User #2. . User #1 receives the approval and is asked to share his/her personal information with User #2. How much information is shared is up to User
#1. This response also includes other encryption keys, such as User #1’s broadcast and system keys.

This process enables exchange of information without exposure to infrastructure and a minimum of back-and-forth to enable the information exchange. The combination of contact requests and required encryption enables several security advantages:

* Encryption can be computationally expensive, which makes mass messaging harder to hide on a compromised machine and slows throughput without placing undue hardships on individuals sending a message to a
few friends.
* Message broadcasts are possible with shared symmetric encryption keys, but they are exchanged only after a contact request exchange is complete.
* Phishing is much more difficult because the sender’s identity is required.
* Only contact requests may be sent to the user with their contact request key. Other types of messages encrypted with it are silently dropped.

*Contact Request: Stage 1 (Lookup)*

Initiated by a client when a user requests contact with another user. The client requests and resolves the other user’s keycard.

*Contact Request: Stage 2 (Initiation)*

Sent after the potential contact’s request key has been received. The client is not required to provide any more personal information than that which is already available in the user’s keycard. However, users
are encouraged to share additional information to help the recipient validate who the sender is. With the exception of non-primary encryption keys, any field found in the link:/spec/clientside/contacts[Contacts
Specification] can be found as part the contact request payload. A sample payload is shown below.

[source,json]
----
{
    "Type" : "sysmessage",
    "SubType" : "ContactReq.1",
    "Version" : "1.0",
    "From" : "3cb11ab3-5482-4154-8ca1-dfa1cc79371c/contoso.com",
    "To" : [ "662679bd-3611-4d5e-a570-52812bdcc6f3/mensago-example.com" ],
    "Date" : "20190905 155323",
    "Sensitivity" : "Public",
    "EntityType" : "individual",
    "Name" : {
        "Given" : "Richard",
        "Family" : "Brannan",
    },
    "Gender" : "Male",
    "Keys" : {
        "Primary" : {
            "Key-Hash" : "BLAKE2B-256:Ce?6fLm)-h{el{F7%A{9R76X_+N{96MQ-qUP?S?Q",
            "Value" : "CURVE25519:h=x-k3#Xvkq6nw;ow(pWSH82r%#gI$WLRf*TRi1a"
        }
    }
}
----

*Contact Request: Stage 3 (Response)*

Sent by a contact request recipient to approve a contact request. Should the recipient approve the request, the approval message is sent with the recipient’s contact information. Unlike the sender’s initial request,
this response contains all of the contact information which the recipient intends to share with the sender. This payload uses the subtype `ContactReq.2`. A recipient can report a contact request as spam to the Abuse address at the server of the sender’s organization.

*Contact Request: Stage 4 (Acknowledgement)*

Sent by the initial contact request sender to fill in any information not initially sent. Additional information is not required for the acknowledgement, but this third step enables a sender to share enough
information to be identified by the recipient in the initial message without sending potentially sensitive information visible to the sender’s provider or the recipient’s provider. This payload uses the subtype `ContactReq.3`. Note that the information sent in this message is supplemental to that sent in the initial request. The recipient’s address book information is updated when this message is received. When this message is sent, the client application should make a note of what information profile was used for future change updates.

*Contact Information Update*

Sent by a user to notify contacts of a change in contact information. The payload sent uses the subtype `ContactUpdate`. The fields and structure are exactly the same as the contact requests, but the update
message is encrypted with the user’s system key, not the recipient’s contact request key. Empty fields which are sent are intended to delete information which was previously available. Note that any client-side
annotations made by the recipients to the sender’s contact information are retained, but the information provided by the sender is not.
