= Notetaking Specification
Jon Yoder <jsyoder@mailfence.com>
v1.0, 2020-02-14

*Status:* Draft +
*Abstract:* Anselus note structure

== Description

It would be completely silly to leave out notetaking abilities on the Anselus platform, given how trivial it would be to implement and how useful it would be.

== Payload Structure

=== Sample User Note

[source,json]
----
 {
    "Type" : "note",
    "Version" : "1.0",
    "Created" : "20200105 123357",
    "Updated" : "20200202 082412",
    "Title" : "Sample Note",
    "Body" : "When at the first I took my pen in hand\nThus for to write, I did not understand\nThat I at all should make a little book\nIn such a mode; nay, I had undertook\nTo make another; which, when almost done,\nBefore I was aware, I this begun.",
    "Tags" : [ "books", "public domain", "John Bunyan" ],
    "Group" : "default",
    "Attachments" : [
        {
            "Name" : "cover.png",
            "Type" : "image/png",
            "Encoding" : "base85",
            "Data" : "iBL{Q4GJ0x0000DNk~Le0000A0000A2nGNE0F5%wy#N3J1am@3R0s$N2z&@+hyVZp7)eAyR2Y?G{Qv*|e+D7|6ETWL6;e+j0BM>85Q>cpXaE2J07*qoM6N<$f&" # <1>
        }
    ]
}
----
<1> The `Data` field has been truncated for the sake of readability

=== Note Fields

.Required Fields
- _Type_ - This field is required for all payloads. It defines the type of payload.

- _Version_ - The messaging API version.

- _Created_ - The UTC date and time of when the note was created. The date MUST be sent using
https://en.wikipedia.org/wiki/ISO_8601[ISO 8601] basic (compact) format. The time MUST be sent in the format HHMMSS. One space MUST be used to separate the two as in the following example: `YYMMDD HHMMSS`.

- _Updated_ - The time the note was last updated. This uses the same format as `created`.

- _Title_ - A string up to 100 characters in length. The characters MUST be valid printable UTF-8 characters or a space. Note that while the field is required, the field itself MAY be empty.

- _Body_ - AnTM-formatted text of any length. Escapement of content for JSON compliance is required.

- _Group_ - The group in which the note may be found. The default value for `group` should be ``default''.

.Optional Fields
- _Tags_ - A list of strings containing UTF-8 user-defined tags.

- _Attachments_ - A list of dictionaries containing attached data using the same format as Anselus messages.

=== Note Content

With notes being merely cloud-synchronized text files, there isn’t much to be said about them. The body content may contain UTF-8 encoded plain text or AnTM-formatted text.
