= Anselus Offline Messaging and File Transport
Jon Yoder <jsyoder@mailfence.com>
v1.0, 2020-10-22

== Introduction

Because of the effort to minimize trust in infrastructure, one might think that underlying transport mechanisms don’t matter. Nothing could be further from the truth. The Anselus transport protocols have been designed to maximize privacy and prevent bad behavior. There are occasions where completely avoiding standard server transport is desired. This specification concerns these situations and tooling to accommodate them.

== Offline Data Format

[source,json]
----
{
    "Item": {
        "ClientItemVersion" : "1.0",
        "KeyHash" : "BLAKE2B-256:uWpi?&AVVKIo&m;O2r=i4tKT|KJ!o~fI0|@l};li"
    },
    "Payload" : "XSALSA20:p!!IiyNgX$CYU+3Hqqb}9wng#^S^-k({8$Ou~NMjT?o6-ARS}uOcGZE1~>_2pLWQt={W1(?L)v&kT*;img18NVf|blhL*_lo-)Th@gQ`vkGy<4MS+M*`A5fI!=U+J;!l1(uhtuR_F>4);OpvDmSITh+|pDcN&i)61Y^n+SLO25gZ>4g&Au3adOrg}+kO%c#E@Db%jpN0rh}$e9Bk;7"
}
----

The format for an offline file is even more minimalistic than a standard Anselus storage file. It is intended to convey as little information about the file except for the requirements to decrypt it. Only the key which matches the KeyHash field will be able to decrypt the associated payload. Files using this format are expected to use the `.ejd` (**E**ncrypted **J**SON **D**ocument) file extension.

== Offline Data Payload Format

Within the payload of an EJD file, multiple files may be attached. Binary data is expected to be Base85-encoded. The payload is expected to be JSON data following the below example:

[source,json]
----
[
	{
		"Name" : "foobar.png",
		"Type" : "image/png",
		"Data" : "iBL{Q4GJ0x0000DNk~Le0000A0000A2nGNE0F5%wy#N3J1am@3R0s$N2z&@+hyVZp7)eAyR2Y?G{Qv*|e+D7|6ETWL6;e+j0BM>85Q>cpXaE2J07*qoM6N<$f&"
	},
	{
		"Name" : "somehaiku.txt",
		"Type" : "text/plain",
		"Data" : "Seek on high bare trails\nsky-reflecting violets\nmountain-top jewels\n"
	}
]
----

== Offline Message Format

Because it can contain any kind of data, an EJD file can be used to transport Anselus messages. A particular format is used for these messages, however.

----
Signature:ED25519:vp6R*W==)9>Us`MA!pz>7yyT&2{I&;`8hQmP<I2uJqu*<OA`O}!a^*e!W5dkVJ%_~V>KQpl;wN+#kXe)
{
    "Type" : "offlinemessage",
    "Version" : "1.0",
    "From" : "3cb11ab3-5482-4154-8ca1-dfa1cc79371c/example.com",
    "Date" : "20201022 120000",
    "ThreadID" : "2280c1f2-d9c0-440c-a182-967b16ba428a",
    "Subject" : "Sample Offline Message",
    "Body" : "The body of an offline message could very well be empty",
    "Attachments" : [
        {
            "Name" : "foobar.png",
            "Type" : "image/png",
            "Data" : "iBL{Q4GJ0x0000DNk~Le0000A0000A2nGNE0F5%wy#N3J1am@3R0s$N2z&@+hyVZp7)eAyR2Y?G{Qv*|e+D7|6ETWL6;e+j0BM>85Q>cpXaE2J07*qoM6N<$f&"
        }
    ]
}
----

The general format of an offline message is not significantly different from a regular user message. In fact, the only real difference is the lack of a `To`, `CC`, or `BCC` field and a different `Type` field value. This is because the user is responsible for transport and delivery of the offline message. Multiple messages may be sent using this format. Each message is its own dictionary of data fields.

To add message integrity and identity, a signature is attached to the message data. The signature may be generated with the user's Contact Request Signing Key or Primary Signing Key. The signature is generated from a minified version of the JSON code which includes the outside brackets. A single CR-LF line ending pair is used to separate the signature from the JSON data. When packaged in an EJD file, they use the `text/x-anselus` MIME type and a UUID for a filename with a `.anem` file extension. Below is an example of an EJD payload carrying an offline message.
