= Mensago Passwordless HTTP Authentication (MPHA)
Jon Yoder <jsyoder@mailfence.com>
v1.0, 2021-05-03

*Status:* Draft +
*Abstract:* Levaraging Mensago to log into websites without a password

== Description

With each web service requiring its own username and password combination, each person is responsible for far too many passwords. People are notoriously bad at creating secure passwords and equally well-known for introducing other vulnerabilities into the authentication process, such as reusing passwords.

Although it has been long established that replacing passwords is necessary, it has been difficult to find a suitable replacement. Thus far the best solution has been to add another authentication factor using a third party authentication application, a text message, or an e-mail. Unfortunately, the first solution is both the most secure and requires extra effort on the user's part, so it has seen the smallest adoption. The other two, although insecure, have been largely used instead. This document describes how a similar method can be used to eliminate the need for the user to remember a password to log into a website.

== How It Works

The primary reason why text messages and e-mail messages as a second factor for authenticating users is that neither is secure. SMS can be rerouted via a SIM attack. E-mail can be intercepted and read. What is needed is an easily-accessible, open standard secure channel over which messages can be sent as an authentication factor. Enter Mensago.

=== Account Setup

Setting up a user account which utilizes Mensago messaging for authentication and user communications is actually easier for both the user and the provider. The user visits a site and requests account setup by entering their Mensago address. The site sends a contact request to the user's address. At this point, the user can not only add the service provider's website to their address book as a service contact, they can also give the service provider other contact information, such as home address, phone number, and other contact information. Just as with any other contact request, the user is in control of what information is given to the provider. Additionally, the service provider can also give the user helpful contact information, such as the product support address and phone number. Once the contact request is complete, the provider and the user have unique encryption keys for exchanging information. A secure channel between the service provider and the user has been established.

=== Authentication

The process for authenticating a user is a challenge-response method similar to that of two Mensago servers authenticating each other for message delivery.

1. User visits a website and navigates to the site login page which requests only the user's Mensago address.
2. User enters their address and clicks Submit.
3. Website looks up the encryption key tied to the user's account.
4. Website creates a random 32-byte challenge and encodes it using https://en.wikipedia.org/wiki/Base32[z-base-32 encoding].
5. A system message is sent to the user which contains the challenge.
6. The website displays a form to enter a 6-digit login code.
7. The user's client application receives the message and displays a popup message containing the login code, which is the first three and last three characters of the encoded challenge.
8. The user enters the login code and clicks Submit.
9. The website receives the code, confirms the match to the challenge, and the user is successfully authenticated.

