= Mensago Passwordless HTTP Authentication
Jon Yoder <jsyoder@mailfence.com>
v1.0, 2021-05-03

*Status:* Draft +
*Abstract:* Levaraging Mensago to log into websites without a password

== Description

With each web service requiring its own username and password combination, each person is responsible for far too many passwords. People are notoriously bad at creating secure passwords and equally well-known for introducing other vulnerabilities into the authentication process, such as reusing passwords.

Although it has been long established that replacing passwords is necessary, it has been difficult to find a suitable replacement. Thus far the best solution has been to add another authentication factor using a third party authentication application, a text message, or an e-mail. Unfortunately, the first solution is both the most secure and requires extra effort on the user's part, so it has seen the smallest adoption. The other two, although insecure, have been largely used instead. This document describes how a similar method can be used to eliminate the need for the user to remember a password to log into a website.

== The Process

The primary reason why text messages and e-mail messages as a second factor for authenticating users is that neither is secure. SMS can be rerouted via a SIM attack. E-mail can be intercepted and read. What is needed is an easily-accessible, open standard secure channel over which messages can be sent as an authentication factor. Enter Mensago.
