= Mensago Security and Threat Modeling
:author: Jon Yoder
:email: jon@yoder.cloud
:revdate: 2021-12-11
:revnumber: 1.0
:description: How Mensago handles security and threat mitigation
:keywords: Mensago, overview, security, threat mitigation
:toc: macro
:table-stripes: odd

toc::[]

== Overview

As a platform, Mensago places minimum trust in infrastructure, plans for compromise, and expects bad behavior. All actors in the interaction model are assumed to be a threat of some kind and are assigned a level of trust based on the actor's assets and potential for attack. 

The threat model focuses on a few specific actors: the client device, the server, other servers, and the network itself, ordered by greatest trust to least. The most trusted device in the model is the client's device. Although some protections can help in the case of a client compromise, it is limited at that point and dependence on proper device administration is required. 

Mensago servers are architected under the assumption that the administrator is under subpoena to provide information to a hostile government entity. Logging is designed specifically to track errors and small-scale bad behavior, such as a password compromise or account bruteforce attempts. An organization's server also functions as a certification authority that stores and vouches for a user's certificate chain. The information given to a server for message delivery is the minimum possible. Because of how the message encryption is structured, it is actually more private to send a message to a recipient at another organization than one inside the same one.

Mensago servers outside the organization are trusted less than an organization's own server. Although each administrator is generally assumed to be minimally competent and trustworthy, it is possible that the administrator could be malicious. Third-party servers can be completely blocked should the need arise.

The network in general is not only not trusted, but assumed to be malicious. End-to-end encryption is utilized to prevent surveillance. Encryption is also leveraged to limit known metadata for parties involved in message delivery. DNSSEC may be used so that dependence on a certificate authority is not needed. Mensago messages are architected such that they could be delivered over a side channel, such as SMTP, instant messaging, Bluetooth, or NFC.

== Spam

Depending on the sources consulted, a large percentage of all e-mail sent is spam, which for the purposes of this project, is defined as unsolicited commercial e-mail. It could be something as simple as a pharmaceutical-related messages from an unreputable source. The Mensago definition of spam also includes communications like unwanted newsletters sent by a legitimate business. Many online vendors use dark patterns to trick users into signing up for a mailing list for their products or simply skip to the end and automatically sign all customers up. Although less malicious, junk e-mail is a major productivity sink because it adds to the clutter a person must deal with. More technical users can manage e-mail subscriptions, but less-savvy users don't know how and don't learn how for a variety of reasons. These users are essentially trapped. This is completely unacceptable.

Spam e-mail is enabled by several different factors:

- A message can be sent to anyone without their consent
- Limitations on traffic volume are a function of server product features and administrator configuration
- Protocols place no limits on the number of recipients a message may have

To eliminate spam, the following provisions have been made:

- The identity of each sender is cryptographically-verifiable and is fixed for the lifetime of each account
- All contact is opt-in, giving users control over who can send them a message
- The protocol allows an individual to send a message to up to 25 recipients. Larger groups of people require use of a shared workspace.
- Server software is required to have traffic controls in place for all workspaces
- Users can utilize the built-in abuse reporting mechanisms to report spammers their administrator
- Administrators can block domains reported to have bad behavior.
- Administrators have an incentive to police their users so that the entire domain doesn't get blocked by other instances.
- Contact requests are the only kind of unsolicited message permitted to be sent, and client software is required to strip embedded links and images from any requests received. Client software is also expected to be engineered to prevent users from sending contact requests with links or images.
- Client software can enable users to automatically block contact requests from specific users or entire domains.

== Phishing

Phishing is a major security threat to computing infrastructure, regardless of its location. Malicious actors rely on phishing as one major way to gain a foothold in a target network. As such, prevention is the name of the game for the Mensago platform. Currently the provisions on the platform should prevent most phishing attacks. These provisions are the following:

- Strong sender and recipient identity prevents malicious actors from pretending to be someone else
- All contact is opt-in
- Traffic limiting prevents sending message broadcasts to entire organizations
- Links and images are stripped from contact requests
- https://github.com/mensago/mensago-docs/blob/master/Safe%20Formatted%20Text%20Markup.adoc[Safe Formatted Text Markup (SFTM)], the rich text format used for Mensago messages, prohibits embedding remote content and executable code of any kind.
- Client software is highly encouraged to deobfuscate links and perform other processing to provide users with information about link targets before the user clicks navigates through the link.
- Client software is also highly encouraged to use https://en.wikipedia.org/wiki/Content_Disarm_%26_Reconstruction[Content Disarm and Reconstruction] techniques to analyze attachments, generate safe previews, and give users a simple way of identifying the potential for an attachment to compromise their system.
- Although a user's contacts are given a certain amount of trust, boundaries to unsafe workflow vectors, e.g. file attachments and browser links, are checked in case a contact has been compromised by a malicious actor to leverage the relationship.

== Network Attacks

Because of such great focus on securing Mensago from user-level attacks, less effort is needed to secure the platform from the network itself.

=== Man in the Middle Attacks

MITM attacks can target an organization's server or a specific user. The greatest danger of MITM server attacks lies in depending on TLS certificates. Current threat management software depends on deep packet inspection to analyze HTTPS traffic. DPI is possible because of TLS certificates. It is recommended that Mensago administrators utilize DNSSEC so that the DANE-like identity protection built into the platform prevents MITM attacks. Clients MUST refuse to connect to a server which fails keycard registration. Users can help prevent user MITM attacks by using https://github.com/mensago/mensago-docs/blob/master/Identity%20Services.adoc#mensago-address-fingerprints[fingerprint-based format] for their address. 

=== Firewall Blocking

State-level actors often block secure services like https://signal.org[Signal]. Working around such infrastructure-level hostility is not easy. Mensago servers are able to communicate on any port so long as the organization's SRV record in DNS is configured to indicate the port expected. Likewise, Mensago messages are transport-independent, so messages can be exchanged between two users so long as the transport software can provide the necessary bridging. Some communications, such as keycard resolution, may require interaction with a server unless the client software provides workarounds.

=== Packet Sniffing

Surveillance and analysis of network traffic is ongoing by more https://en.wikipedia.org/wiki/Global_surveillance_disclosures_(2013%E2%80%93present)[government agencies] than just the NSA and GCHQ. TLS provides some protection from this, but client software is also permitted to add random amounts of padding to message payloads in addition to the wire-level padding.
